name: shopping_cart
description: "Uma aplicação de carrinho de compras"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  dio: ^5.9.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  mockito: ^5.4.5
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
